# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

target 'VKMessenger' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod "VK-ios-sdk"
  pod 'R.swift'

  # Pods for VKMessenger

end
